/**
 * Shared hooks — URL state, pagination, permissions, auth, connectivity.
 *
 * `students.ts` is the reference implementation for [8.4.3]'s query
 * cache/invalidation conventions — `query-keys.ts`'s hierarchical
 * factory, `retry.ts`'s shared 4xx-doesn't-retry predicate, and
 * `tenant.ts`'s cache-clearing tenant switch. Later entities' hooks
 * should mirror `students.ts`'s shape rather than reinvent it — see
 * `ui/README.md`'s "Hooks" section for the full pattern write-up.
 */
export { ApprovalCancelledError, ApprovalModalHostProvider } from './approval';
export { createEntityKeys, type EntityKeys } from './query-keys';
export { shouldRetryQuery } from './retry';
export { useOnline } from './use-online';
export { useRecentItems, type RecentItem, type UseRecentItemsResult } from './recent-items';
export { useQueryFreshness } from './use-query-freshness';
export { useSyncQueue } from './use-sync-queue';
export { switchActiveTenant } from './tenant';
export {
  activate,
  changePassword,
  forgotPassword,
  login,
  logout,
  logoutAll,
  requestOtp,
  resetPassword,
  sessionsQueryOptions,
  useRevokeSession,
  verifyOtp,
  type SessionDto,
} from './auth';
export { useAccessToken, useActiveRole, useActiveTenant, useCurrentUserId } from './auth-state';
export {
  currentUserQueryOptions,
  userKeys,
  userQueryOptions,
  usersQueryOptions,
  useAdminResetPassword,
  useConfirmPhoneChange,
  useCreateUser,
  useCurrentUser,
  useRemoveMember,
  useRequestContactChange,
  useResendInvitation,
  useRevokeInvitation,
  useUpdateOwnProfile,
  useUpdateUser,
  useUser,
  useUsers,
  type AdminResetPasswordResult,
  type ContactChangeInput,
  type ContactChangeRequestResult,
  type CreateUserInput,
  type CreateUserResult,
  type InvitationResult,
  type PaginatedUsers,
  type StaffUser,
  type UpdateOwnProfileInput,
  type UpdateUserInput,
  type UserListFilters,
  type UserRoleFilter,
} from './users';
export {
  invitationBatchQueryOptions,
  useDispatchInvitations,
  useInvitationBatch,
  useInvitationPreview,
  type BatchInviteSelection,
  type InviteBatchStatus,
  type InviteChannel,
  type InviteDispatchResult,
  type InvitePreviewEntry,
  type InvitePreviewResult,
  type InviteSkipReason,
  type InviteSkippedEntry,
} from './invitations';
export {
  teacherKeys,
  teachersQueryOptions,
  useCreateTeacher,
  useTeachers,
  useUpdateTeacher,
  type CreateTeacherInput,
  type PaginatedTeachers,
  type Teacher,
  type TeacherListFilters,
  type UpdateTeacherInput,
} from './teachers';
export {
  myStudentsQueryOptions,
  studentIdsQueryOptions,
  studentKeys,
  studentQueryOptions,
  studentsQueryOptions,
  useCreateStudent,
  useDeleteStudent,
  useMyStudents,
  useStudent,
  useStudentIds,
  useStudents,
  useStudentSearch,
  useUpdateStudent,
  useUpdateStudentEnrollmentStatus,
  useUpdateStudentPreferredCommunication,
  type CreateStudentInput,
  type EnrollmentStatus,
  type PaginatedStudents,
  type PreferredCommunication,
  type Student,
  type StudentIdsFilters,
  type StudentIdsResult,
  type StudentListFilters,
  type StudentSortField,
  type UpdateStudentInput,
} from './students';
export {
  guardianKeys,
  guardianQueryOptions,
  guardiansQueryOptions,
  myGuardianQueryOptions,
  useCreateGuardian,
  useDeleteGuardian,
  useGuardian,
  useGuardians,
  useMyGuardian,
  useUpdateGuardian,
  useUpdateMyGuardian,
  type CreateGuardianInput,
  type Guardian,
  type GuardianListFilters,
  type PaginatedGuardians,
  type UpdateGuardianInput,
  type UpdateOwnGuardianInput,
} from './guardians';
export {
  cartKeys,
  paymentKeys,
  useCart,
  useCheckout,
  usePayment,
  usePaymentsByGuardian,
  usePaymentsByStudent,
  useReversePayment,
  useStudentFeeSummary,
  type CartBill,
  type CartResult,
  type CartStudent,
  type CartSuggestion,
  type ChangeHandling,
  type CheckoutInput,
  type CheckoutLine,
  type CheckoutResult,
  type FamilyPayment,
  type Payment,
  type PaymentDetail,
  type ReverseLaterPaymentsFirstDetails,
  type ReversePaymentInput,
  type ReversePaymentResult,
  type StudentFee,
  type StudentFeeSummary,
} from './payments';
export {
  discountRulesQueryOptions,
  useCreateDiscountRule,
  useDeleteDiscountRule,
  useDiscountRules,
  useUpdateDiscountRule,
  type CreateDiscountRuleInput,
  type DeleteDiscountRuleInput,
  type DiscountKind,
  type DiscountRule,
  type UpdateDiscountRuleInput,
} from './discount-rules';
export {
  enrollmentKeys,
  useStudentEnrollments,
  useCurrentEnrollment,
  useCreateEnrollment,
  useUpdateEnrollment,
  type Enrollment,
  type CreateEnrollmentInput,
  type UpdateEnrollmentInput,
} from './enrollments';
export {
  communicationLogKeys,
  useCommunicationLog,
  useGuardianCommunicationLogs,
  useSendCommunication,
  useStudentCommunicationLogs,
  useLastReminders,
  type CommunicationLog,
  type LastReminder,
  type SendCommunicationInput,
} from './communications';
export {
  auditLogKeys,
  auditLogsQueryOptions,
  useAuditLogs,
  useAuditLogsByEntity,
  useLoginAuditLogs,
  type AuditLog,
  type AuditLogListFilters,
  type PaginatedAuditLogs,
} from './audit-logs';
export { hasPermission, useHasPermission } from './permissions';
export {
  classSubjectsKey,
  classSubjectsQueryOptions,
  subjectKeys,
  subjectsQueryOptions,
  useAttachClassSubject,
  useClassSubjects,
  useCreateSubject,
  useDeleteSubject,
  useDetachClassSubject,
  useSubjects,
  useUpdateSubject,
  type AttachClassSubjectInput,
  type ClassSubject,
  type CreateSubjectInput,
  type PaginatedSubjects,
  type Subject,
  type SubjectListFilters,
  type UpdateSubjectInput,
} from './subjects';
export {
  classKeys,
  classesQueryOptions,
  classQueryOptions,
  classSectionsKey,
  classSectionsQueryOptions,
  classTeachersQueryOptions,
  organisationVocabularyQueryOptions,
  useClass,
  useClasses,
  useClassSections,
  useClassTeachers,
  useCreateClass,
  useCreateSection,
  useDeleteClass,
  useDeleteSection,
  useOrganisationVocabulary,
  useUpdateClass,
  useUpdateSection,
  type Class,
  type ClassListFilters,
  type ClassSection,
  type ClassSectionWithCount,
  type ClassTeacher,
  type ClassWithCounts,
  type CreateClassInput,
  type CreateSectionInput,
  type OrganisationVocabulary,
  type PaginatedClasses,
  type UpdateClassInput,
  type UpdateSectionInput,
} from './classes';
export {
  examComponentsAllQueryOptions,
  examComponentsKey,
  examComponentsQueryOptions,
  examKeys,
  examProgressQueryOptions,
  examQueryOptions,
  examsQueryOptions,
  subjectChoiceOptionsKey,
  subjectChoiceOptionsQueryOptions,
  useCopyExamComponents,
  useCreateExam,
  useCreateExamComponent,
  useDeleteExamComponent,
  useExam,
  useExamComponents,
  useExamComponentsAll,
  useExamProgress,
  useExams,
  useSetSubjectChoice,
  useSubjectChoiceOptions,
  useUpdateExam,
  useUpdateExamComponent,
  type CopyExamComponentsInput,
  type CopyExamComponentsResult,
  type CreateExamComponentInput,
  type CreateExamInput,
  type Exam,
  type ExamComponent,
  type ExamListFilters,
  type ExamProgress,
  type PaginatedExams,
  type SetSubjectChoiceInput,
  type SubjectChoiceOption,
  type UpdateExamComponentInput,
  type UpdateExamInput,
} from './exams';
export {
  attendanceKeys,
  lowAttendanceKey,
  lowAttendanceQueryOptions,
  mySectionsQueryOptions,
  recordHistoryKey,
  recordHistoryQueryOptions,
  registerMatrixKey,
  registerMatrixQueryOptions,
  sectionRegisterKey,
  sectionRegisterQueryOptions,
  sectionSummaryKey,
  sectionSummaryQueryOptions,
  studentAttendanceDaysKey,
  studentAttendanceDaysQueryOptions,
  studentAttendanceSummaryKey,
  studentAttendanceSummaryQueryOptions,
  useCorrectRecord,
  useLowAttendance,
  useMySections,
  useRecordHistory,
  useRegisterMatrix,
  useSectionRegister,
  useSectionSummary,
  useStudentAttendanceDays,
  useStudentAttendanceSummary,
  useSubmitRegister,
  type AttendanceListFilters,
  type AttendanceSummary,
  type CorrectRecordInput,
  type CorrectRecordVariables,
  type LowAttendanceFilters,
  type LowAttendanceFlag,
  type LowAttendanceListResponse,
  type MySection,
  type PutRegisterInput,
  type Register,
  type RecordHistoryEntry,
  type RecordHistoryResponse,
  type RegisterEntry,
  type RegisterMatrix,
  type RegisterMatrixRow,
  type RegisterStudent,
  type SectionSummary,
  type StudentAttendanceDay,
  type StudentSummaryRow,
  type SubmitRegisterResult,
} from './attendance';
export {
  collectionsReportKeys,
  collectionsReportQueryOptions,
  downloadCollectionsReportCsv,
  useCollectionsReport,
  type CollectionsByCollector,
  type CollectionsByDay,
  type CollectionsByFeeType,
  type CollectionsByMethod,
  type CollectionsReportFilters,
  type CollectionsReportResponse,
  type CollectionsReportTotals,
} from './reports';
export {
  collectFailedStudentIds,
  REMINDER_BATCH_POLL_MS,
  reminderBatchKeys,
  reminderBatchLogsKey,
  reminderBatchLogsKeyPrefix,
  reminderBatchLogsQueryOptions,
  reminderBatchQueryOptions,
  reminderBatchesQueryOptions,
  useBulkReminderPreview,
  useReminderBatch,
  useReminderBatchLogs,
  useReminderBatches,
  useSendBulkReminder,
  useSendSingleReminder,
  useSingleReminderPreview,
  type BulkPreviewSkipped,
  type BulkPreviewStudent,
  type BulkReminderPreview,
  type PaginatedReminderBatchLogs,
  type PaginatedReminderBatches,
  type ReminderBatchListFilters,
  type ReminderBatchListItem,
  type ReminderBatchLog,
  type ReminderBatchResponse,
  type ReminderPreview,
  type ReminderPreviewRecipient,
  type SendBulkReminderInput,
  type SendSingleReminderInput,
  type SingleReminderResult,
  type SingleReminderVariables,
  type SkippedGuardian,
  type SkippedRecipient,
} from './reminders';
export {
  academicYearKeys,
  academicYearQueryOptions,
  academicYearsQueryOptions,
  academicYearStatsQueryOptions,
  useAcademicYear,
  useAcademicYears,
  useAcademicYearStats,
  useCreateAcademicYear,
  useDeleteAcademicYear,
  useSetCurrentAcademicYear,
  useUpdateAcademicYear,
  type AcademicYear,
  type AcademicYearListFilters,
  type AcademicYearStats,
  type CreateAcademicYearInput,
  type PaginatedAcademicYears,
  type UpdateAcademicYearInput,
} from './academic-years';
export {
  calendarSettingsKeys,
  calendarSettingsQueryOptions,
  useCalendarSettings,
  type CalendarSettings,
} from './calendar-settings';
export {
  termKeys,
  termsQueryOptions,
  useCreateTerm,
  useDeleteTerm,
  useReorderTerms,
  useTerms,
  useUpdateTerm,
  type AcademicTerm,
  type CreateTermInput,
  type ReorderTermsInput,
  type UpdateTermInput,
} from './calendar-terms';
export {
  calendarEventKeys,
  calendarEventsQueryOptions,
  publicHolidayKeys,
  useAddPublicHolidays,
  useCalendarEvent,
  useCalendarEvents,
  useCreateCalendarEvent,
  useDeleteCalendarEvent,
  usePublicHolidaySuggestions,
  usePublishCalendarEvent,
  useUpdateCalendarEvent,
  type CalendarEvent,
  type CalendarEventList,
  type CalendarEventsFilters,
  type CreateCalendarEventInput,
  type UpdateCalendarEventInput,
} from './calendar-events';
export {
  calendarFeedKeys,
  useCalendarFeed,
  useRegenerateCalendarFeed,
  type CalendarFeed,
} from './calendar-feed';
export {
  downloadCalendarExport,
  downloadCalendarImportTemplate,
  useCloneCalendar,
  useCommitCalendarImport,
  useValidateCalendarImport,
  type CalendarImportCommitResponse,
  type CalendarImportRow,
  type CalendarImportRowStatus,
  type CalendarImportSummary,
  type CalendarImportValidateResponse,
} from './calendar-import';
export {
  feeStructureKeys,
  feeStructureQueryOptions,
  feeStructuresQueryOptions,
  useCreateFeeStructure,
  useDeleteFeeStructure,
  useFeeStructure,
  useFeeStructures,
  useUpdateFeeStructure,
  type CreateFeeStructureInput,
  type FeeStructure,
  type FeeStructureListFilters,
  type PaginatedFeeStructures,
  type UpdateFeeStructureInput,
} from './fee-structures';
export {
  useGenerateFees,
  useGenerateFeesPreview,
  type DuplicateAction,
  type GenerateFeesDuplicate,
  type GenerateFeesInactiveStudent,
  type GenerateFeesInput,
  type GenerateFeesPreviewInput,
  type GenerateFeesPreviewResult,
  type GenerateFeesRequest,
  type GenerateFeesResult,
  type GenerateFeesScope,
  type PeriodType,
} from './fee-generation';
export {
  useValidateStudentUpload,
  useCommitStudentUpload,
  type BulkUploadError,
  type BulkUploadResult,
  type StudentUploadPreviewRow,
  type StudentUploadSummary,
} from './bulk-upload';
export {
  backupKeys,
  downloadBackup,
  downloadWorkbookTemplate,
  useBackupJob,
  useBackupJobs,
  usePinBackupJob,
  usePlatformBackupHealth,
  useRequestBackup,
  useRestoreBackup,
  useValidateBackup,
  type RequestRestoreResponse,
  type RestoreBackupInput,
  type RestoreSummary,
  type TabSummaryDto,
  type ValidateTotalsDto,
  type WorkbookJob,
  type WorkbookJobKind,
  type WorkbookJobListFilters,
  type WorkbookJobProgress,
  type WorkbookJobRequester,
  type WorkbookJobSource,
  type WorkbookJobStatus,
  type PaginatedWorkbookJobs,
  type PlatformSchoolBackupHealth,
} from './backup';
export {
  useBulkUploadPreview,
  type BulkImportError,
  type PreviewResult,
  type BulkUploadPreviewState,
} from './use-bulk-upload-preview';
export {
  ROUTE_FOCUS_MAX_PENDING_RETRIES,
  useRouteFocus,
  type UseRouteFocusOptions,
} from './use-route-focus';
export { useDebouncedValue } from './use-debounce';
export { useEntityLabel } from './entity-label';
export { useContainerWidth } from './use-container-width';
export {
  invoiceKeys,
  invoiceQueryOptions,
  invoiceSharesQueryOptions,
  invoicesQueryOptions,
  openPrintableInvoice,
  useCreateInvoice,
  useInvoice,
  useInvoiceSendCandidates,
  useInvoiceShares,
  useInvoices,
  usePrintInvoice,
  usePublicInvoice,
  useRevokeShare,
  useSendInvoice,
  useShareInvoice,
  type CreateInvoiceInput,
  type CreateInvoiceShareResult,
  type Invoice,
  type InvoiceKind,
  type InvoiceListFilters,
  type InvoiceShareToken,
  type InvoiceStatus,
  type InvoiceWithSnapshot,
  type PaginatedInvoices,
  type PublicInvoiceReceipt,
  type SendInvoiceInput,
  type SendInvoiceMedium,
} from './invoices';
export {
  feeDuesKeys,
  feeDuesQueryOptions,
  useFeeDues,
  type FeeDueEntry,
  type FeeDueRow,
  type FeeDuesFilters,
  type FeeDuesSortBy,
  type PaginatedFeeDues,
  type SortOrder,
} from './fee-dues';
export {
  useStudentWallet,
  walletKeys,
  type FamilyStudentWallet,
  type FamilyWalletTransaction,
  type StudentWallet,
  type WalletTransaction,
} from './wallet';
export {
  feeGenerationBillsQueryOptions,
  feeGenerationQueryOptions,
  feeGenerationsKeys,
  feeGenerationsQueryOptions,
  useDeleteFeeGeneration,
  useFeeGeneration,
  useFeeGenerationBills,
  useFeeGenerations,
  usePatchFeeGeneration,
  useRemoveBatchStudent,
  useRemoveUncollected,
  type FeeGeneration,
  type FeeGenerationBill,
  type FeeGenerationBillsFilters,
  type FeeGenerationsFilters,
  type FeeGenerationStructureSnapshot,
  type PaginatedFeeGenerationBills,
  type PaginatedFeeGenerations,
  type PatchFeeGenerationConflict,
  type PatchFeeGenerationInput,
  type RemoveBatchStudentInput,
  type RemoveUncollectedResult,
} from './fee-generations';
export {
  usePaletteSearch,
  type PaletteSearchResults,
  type PaletteSearchStudent,
  type PaletteSearchGuardian,
  type PaletteSearchStaff,
  type PaletteSearchInvoice,
  type PaletteSearchPayment,
} from './palette-search';
export { useNotifications, useUnreadNotificationCount } from './notifications';
export {
  recurringScheduleKeys,
  recurringSchedulesQueryOptions,
  recurringScheduleQueryOptions,
  studentScheduleCoverageKeys,
  studentScheduleCoverageQueryOptions,
  useRecurringSchedules,
  useRecurringSchedule,
  useCreateRecurringSchedule,
  useUpdateRecurringSchedule,
  useDeleteRecurringSchedule,
  useCloneRecurringSchedule,
  schedulePreviewKeys,
  schedulePreviewQueryOptions,
  useSchedulePreview,
  useAddScheduleExclusion,
  useRemoveScheduleExclusion,
  useStudentScheduleCoverage,
  useIncludeStudentInSchedule,
  familyStudentScheduleKeys,
  familyStudentSchedulesQueryOptions,
  useFamilyStudentSchedules,
  ISO_WEEKDAYS,
  type RecurringSchedule,
  type RecurringScheduleDetail,
  type RecurringScheduleRule,
  type RecurringScheduleRuleKind,
  type RecurringScheduleAudience,
  type RecurringScheduleExclusion,
  type MonthlyRuleDay,
  type Weekday,
  type AddExclusionInput,
  type CreateRecurringScheduleInput,
  type UpdateRecurringScheduleInput,
  type CloneScheduleResult,
  type SchedulePreview,
  type SchedulePreviewStudent,
  type RecurringScheduleListFilters,
  type StudentScheduleItem,
  type FamilyStudentSchedule,
} from './recurring-schedules';
export {
  schoolsKeys,
  schoolSettingsKeys,
  schoolSettingsQueryOptions,
  useSchools,
  useSchoolSettings,
  useUpdateSchoolSettings,
  useTestSchoolConnection,
  useProvisionSchool,
  type SchoolSummary,
  type ProvisionSchoolAdminInput,
  type ProvisionSchoolInput,
  type ProvisionSchoolResult,
  type MaskedSecret,
  type AttendancePolicySettings,
  type AuthSettings,
  type MaskedRegionSettings,
  type MaskedGreenwebSmsSettings,
  type MaskedMimSmsSettings,
  type MaskedSmsSettings,
  type MaskedWhatsAppSettings,
  type MaskedEmailSettings,
  type MaskedMessengerSettings,
  type MaskedCommunicationsSettings,
  type MaskedTenantSettings,
  type BackupSettings,
  type FeesSettings,
  type OrganisationSettings,
  type FeesSettingsInput,
  type LateFeeSetting,
  type ConnectionTestResult,
  type TenantSettingsInput,
  type TestConnectionInput,
  type TestableMedium,
  useSchoolStats,
  schoolStatsQueryOptions,
  type SchoolStats,
  useUpdateSchoolStatus,
  type SchoolStatusResult,
  type UpdateSchoolStatusInput,
  useSchoolAdmins,
  schoolAdminsQueryOptions,
  schoolAdminsKeys,
  type SchoolAdminListItem,
  useAddSchoolAdmin,
  type AddSchoolAdminInput,
  useResendSchoolAdminInvitation,
  useRevokeSchoolAdminInvitation,
} from './school-settings';
export {
  useSchoolProfile,
  useUpdateSchoolProfile,
  useUploadSchoolLogo,
  useRemoveSchoolLogo,
  type SchoolProfile,
  type UpdateSchoolProfileInput,
} from './school-profile';
export { useDensity, type DensityMode } from './use-density';
export {
  publicHolidaySetKeys,
  publicHolidaySetsQueryOptions,
  publicHolidaySetQueryOptions,
  useHolidaySets,
  useHolidaySet,
  useFetchHolidaySet,
  useUpdateHolidaySetEntries,
  usePublishHolidaySet,
  useUnpublishHolidaySet,
  type PublicHolidaySet,
  type PublicHolidayEntry,
  type HolidayEntryInput,
  type FetchHolidaySetInput,
} from './public-holiday-sets';
export {
  gradingScaleKeys,
  gradingScaleQueryOptions,
  gradingScalesQueryOptions,
  useConfirmBands,
  useCopyGradingScale,
  useCreateGradingScale,
  useDeleteGradingScale,
  useGradingScale,
  useGradingScales,
  usePreviewBands,
  useUpdateGradingScale,
  type BandInput,
  type ConfirmBandsResult,
  type CopyScaleInput,
  type CreateGradingScaleInput,
  type GradingBand,
  type GradingScale,
  type GradingScaleListFilters,
  type RecomputePreviewResult,
  type RecomputeProblem,
  type UpdateGradingScaleInput,
} from './grading';
export {
  smsCreditsKeys,
  smsCreditsQueryOptions,
  useGrantSmsCredits,
  useSmsCredits,
  type GrantSmsCreditsInput,
  type SmsCreditLedgerItem,
  type SmsCreditsFilters,
  type SmsCreditsResponse,
} from './sms-credits';
