/**
 * Shared hooks — URL state, pagination, permissions, auth, connectivity.
 *
 * `students.ts` is the reference implementation for [8.4.3]'s query
 * cache/invalidation conventions — `query-keys.ts`'s hierarchical
 * factory, `retry.ts`'s shared 4xx-doesn't-retry predicate, and
 * `tenant.ts`'s cache-clearing tenant switch. Later entities' hooks
 * should mirror `students.ts`'s shape rather than reinvent it — see
 * `ui/README.md`'s "Hooks" section for the full pattern write-up.
 */
export { createEntityKeys, type EntityKeys } from './query-keys';
export { shouldRetryQuery } from './retry';
export { useOnline } from './use-online';
export { useQueryFreshness } from './use-query-freshness';
export { useSyncQueue } from './use-sync-queue';
export { switchActiveTenant } from './tenant';
export { changePassword, login, logout, logoutAll } from './auth';
export { useAccessToken, useActiveRole, useActiveTenant, useCurrentUserId } from './auth-state';
export {
  currentUserQueryOptions,
  userKeys,
  userQueryOptions,
  usersQueryOptions,
  useCreateUser,
  useCurrentUser,
  useRemoveMember,
  useUpdateOwnProfile,
  useUpdateUser,
  useUser,
  useUsers,
  type CreateUserInput,
  type CreateUserResult,
  type PaginatedUsers,
  type StaffUser,
  type UpdateOwnProfileInput,
  type UpdateUserInput,
  type UserListFilters,
  type UserRoleFilter,
} from './users';
export {
  teacherKeys,
  teachersQueryOptions,
  useCreateTeacher,
  useTeachers,
  useUpdateTeacher,
  type CreateTeacherInput,
  type PaginatedTeachers,
  type Teacher,
  type TeacherListFilters,
  type UpdateTeacherInput,
} from './teachers';
export {
  myStudentsQueryOptions,
  studentKeys,
  studentQueryOptions,
  studentsQueryOptions,
  useCreateStudent,
  useDeleteStudent,
  useMyStudents,
  useStudent,
  useStudents,
  useUpdateStudent,
  useUpdateStudentEnrollmentStatus,
  useUpdateStudentPreferredCommunication,
  type CreateStudentInput,
  type EnrollmentStatus,
  type PaginatedStudents,
  type PreferredCommunication,
  type Student,
  type StudentListFilters,
  type StudentSortField,
  type UpdateStudentInput,
} from './students';
export {
  guardianKeys,
  guardianQueryOptions,
  guardiansQueryOptions,
  myGuardianQueryOptions,
  useCreateGuardian,
  useDeleteGuardian,
  useGuardian,
  useGuardians,
  useMyGuardian,
  useUpdateGuardian,
  useUpdateMyGuardian,
  type CreateGuardianInput,
  type Guardian,
  type GuardianListFilters,
  type PaginatedGuardians,
  type UpdateGuardianInput,
  type UpdateOwnGuardianInput,
} from './guardians';
export {
  paymentKeys,
  useCreatePayment,
  usePaymentsByGuardian,
  usePaymentsByStudent,
  useStudentFeeSummary,
  useRecordPaymentWithAllocation,
  type CreatePaymentInput,
  type FamilyPayment,
  type Payment,
  type PaymentAllocationInput,
  type RecordPaymentWithAllocationInput,
  type StudentFee,
  type StudentFeeSummary,
} from './payments';
export {
  enrollmentKeys,
  useStudentEnrollments,
  useCurrentEnrollment,
  useCreateEnrollment,
  useUpdateEnrollment,
  type Enrollment,
  type CreateEnrollmentInput,
  type UpdateEnrollmentInput,
} from './enrollments';
export {
  communicationLogKeys,
  useCommunicationLog,
  useGuardianCommunicationLogs,
  useSendCommunication,
  useStudentCommunicationLogs,
  useLastReminders,
  type CommunicationLog,
  type LastReminder,
  type SendCommunicationInput,
} from './communications';
export {
  auditLogKeys,
  auditLogsQueryOptions,
  useAuditLogs,
  useAuditLogsByEntity,
  useLoginAuditLogs,
  type AuditLog,
  type AuditLogListFilters,
  type PaginatedAuditLogs,
} from './audit-logs';
export { hasPermission, useHasPermission } from './permissions';
export {
  classKeys,
  classesQueryOptions,
  classQueryOptions,
  classSectionsKey,
  classSectionsQueryOptions,
  classTeachersQueryOptions,
  useClass,
  useClasses,
  useClassSections,
  useClassTeachers,
  useCreateClass,
  useCreateSection,
  useDeleteClass,
  useDeleteSection,
  useUpdateClass,
  useUpdateSection,
  type Class,
  type ClassListFilters,
  type ClassSection,
  type ClassSectionWithCount,
  type ClassTeacher,
  type ClassWithCounts,
  type CreateClassInput,
  type CreateSectionInput,
  type PaginatedClasses,
  type UpdateClassInput,
  type UpdateSectionInput,
} from './classes';
export {
  collectFailedStudentIds,
  REMINDER_BATCH_POLL_MS,
  reminderBatchKeys,
  reminderBatchLogsKey,
  reminderBatchLogsKeyPrefix,
  reminderBatchLogsQueryOptions,
  reminderBatchQueryOptions,
  reminderBatchesQueryOptions,
  useBulkReminderPreview,
  useReminderBatch,
  useReminderBatchLogs,
  useReminderBatches,
  useSendBulkReminder,
  useSendSingleReminder,
  useSingleReminderPreview,
  type BulkPreviewSkipped,
  type BulkPreviewStudent,
  type BulkReminderPreview,
  type PaginatedReminderBatchLogs,
  type PaginatedReminderBatches,
  type ReminderBatchListFilters,
  type ReminderBatchListItem,
  type ReminderBatchLog,
  type ReminderBatchResponse,
  type ReminderPreview,
  type ReminderPreviewRecipient,
  type SendBulkReminderInput,
  type SendSingleReminderInput,
  type SingleReminderResult,
  type SingleReminderVariables,
  type SkippedGuardian,
  type SkippedRecipient,
} from './reminders';
export {
  academicYearKeys,
  academicYearQueryOptions,
  academicYearsQueryOptions,
  academicYearStatsQueryOptions,
  useAcademicYear,
  useAcademicYears,
  useAcademicYearStats,
  useCreateAcademicYear,
  useDeleteAcademicYear,
  useSetCurrentAcademicYear,
  useUpdateAcademicYear,
  type AcademicYear,
  type AcademicYearListFilters,
  type AcademicYearStats,
  type CreateAcademicYearInput,
  type PaginatedAcademicYears,
  type UpdateAcademicYearInput,
} from './academic-years';
export {
  feeStructureKeys,
  feeStructureQueryOptions,
  feeStructuresQueryOptions,
  useCreateFeeStructure,
  useDeleteFeeStructure,
  useFeeStructure,
  useFeeStructures,
  useUpdateFeeStructure,
  type CreateFeeStructureInput,
  type FeeStructure,
  type FeeStructureListFilters,
  type FeeStructureStudent,
  type PaginatedFeeStructures,
  type UpdateFeeStructureInput,
} from './fee-structures';
export { useGenerateFees, type GenerateFeesInput, type GenerateFeesResult } from './fee-generation';
export {
  useBulkUploadStudents,
  type BulkUploadError,
  type BulkUploadResult,
  type BulkUploadStudentsInput,
} from './bulk-upload';
export { useRouteFocus, type UseRouteFocusOptions } from './use-route-focus';
export { useDebouncedValue } from './use-debounce';
export {
  invoiceKeys,
  invoicesQueryOptions,
  openPrintableInvoice,
  useCreateInvoice,
  useInvoice,
  useInvoices,
  type CreateInvoiceInput,
  type Invoice,
  type InvoiceListFilters,
  type InvoiceStatus,
  type PaginatedInvoices,
} from './invoices';
export {
  feeDuesKeys,
  feeDuesQueryOptions,
  useFeeDues,
  type FeeDueEntry,
  type FeeDueRow,
  type FeeDuesFilters,
  type FeeDuesSortBy,
  type PaginatedFeeDues,
  type SortOrder,
} from './fee-dues';
export {
  useGlobalSearch,
  type GlobalSearchEntityResult,
  type GlobalSearchResults,
  type TeacherProfile,
} from './global-search';
export { useNotifications, useUnreadNotificationCount } from './notifications';
export {
  schoolsKeys,
  schoolSettingsKeys,
  useSchools,
  useSchoolSettings,
  useUpdateSchoolSettings,
  useTestSchoolConnection,
  type SchoolSummary,
  type MaskedSecret,
  type MaskedRegionSettings,
  type MaskedGreenwebSmsSettings,
  type MaskedMimSmsSettings,
  type MaskedSmsSettings,
  type MaskedWhatsAppSettings,
  type MaskedEmailSettings,
  type MaskedMessengerSettings,
  type MaskedCommunicationsSettings,
  type MaskedTenantSettings,
  type ConnectionTestResult,
  type TenantSettingsInput,
  type TestConnectionInput,
  type TestableMedium,
} from './school-settings';
export { useDensity, type DensityMode } from './use-density';
