import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1784175065078 implements MigrationInterface {
    name = 'InitialSchema1784175065078'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('SUPER_ADMIN', 'ADMIN', 'ACCOUNTANT', 'TEACHER', 'PARENT', 'STUDENT', 'EXECUTIVE')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(100), "phone" character varying(20), "password_hash" character varying(255), "role" "public"."users_role_enum" NOT NULL, "status" "public"."users_status_enum" NOT NULL DEFAULT 'ACTIVE', "full_name" character varying(100) NOT NULL, "profile_picture_url" character varying(255), "preferences" jsonb, "last_login_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a000cca60bcf04454e72769949" ON "users" ("phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "academic_years" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "is_current" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2021b90bfbfa6c9da7df34ca1cf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_12a99ca8a701651b6ff5d6612e" ON "academic_years" ("is_current") WHERE is_current = true`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_645d0f115fa85aaecffdc11cba" ON "academic_years" ("name") `);
        await queryRunner.query(`CREATE TABLE "classes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "numeric_grade" integer, "academic_year_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e207aa15404e9b2ce35910f9f7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_94109a89dd3240577e832b96df" ON "classes" ("name", "academic_year_id") `);
        await queryRunner.query(`CREATE TABLE "class_sections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "class_id" uuid NOT NULL, "section_name" character varying(20) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e33e202b8db5a2bb2d6d6f0c3b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_63d2faa7e6351f234ede380634" ON "class_sections" ("class_id", "section_name") `);
        await queryRunner.query(`CREATE TYPE "public"."guardians_preferred_communication_enum" AS ENUM('SMS', 'WHATSAPP', 'EMAIL', 'PHONE_CALL', 'MESSENGER')`);
        await queryRunner.query(`CREATE TABLE "guardians" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "full_name" character varying(100) NOT NULL, "relationship" character varying(50) NOT NULL, "phone" character varying(20), "email" character varying(100), "alternate_phone" character varying(20), "address" text, "occupation" character varying(100), "preferred_communication" "public"."guardians_preferred_communication_enum" NOT NULL DEFAULT 'SMS', "is_primary_contact" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "REL_f1d05a3a2d70db0a25479b6718" UNIQUE ("user_id"), CONSTRAINT "PK_3dcf02f3dc96a2c017106f280be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2822ea52513239fdd508c016e3" ON "guardians" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_0649f376bac8d9709fb4050fac" ON "guardians" ("phone") `);
        await queryRunner.query(`CREATE TYPE "public"."students_preferred_communication_enum" AS ENUM('SMS', 'WHATSAPP', 'EMAIL', 'PHONE_CALL', 'MESSENGER')`);
        await queryRunner.query(`CREATE TYPE "public"."students_enrollment_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'TRANSFERRED', 'GRADUATED')`);
        await queryRunner.query(`CREATE TABLE "students" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "full_name" character varying(100) NOT NULL, "registration_number" character varying(50) NOT NULL, "roll_number" integer NOT NULL, "class_section_id" uuid NOT NULL, "date_of_birth" date NOT NULL, "gender" character varying(10), "home_address" text, "preferred_communication" "public"."students_preferred_communication_enum" NOT NULL DEFAULT 'SMS', "enrollment_status" "public"."students_enrollment_status_enum" NOT NULL DEFAULT 'ACTIVE', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_82946fdb5652b83cacb81e9083e" UNIQUE ("registration_number"), CONSTRAINT "REL_fb3eff90b11bddf7285f9b4e28" UNIQUE ("user_id"), CONSTRAINT "PK_7d7f07271ad4ce999880713f05e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ca01941430b7d99b013e6c6948" ON "students" ("class_section_id", "roll_number") `);
        await queryRunner.query(`CREATE TYPE "public"."student_fees_status_enum" AS ENUM('PENDING', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'WAIVED', 'ADVANCE')`);
        await queryRunner.query(`CREATE TABLE "student_fees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "student_id" uuid NOT NULL, "academic_year_id" uuid NOT NULL, "month" integer NOT NULL, "year" integer NOT NULL, "total_amount" numeric(10,2) NOT NULL, "paid_amount" numeric(10,2) NOT NULL DEFAULT '0', "discount_amount" numeric(10,2) NOT NULL DEFAULT '0', "status" "public"."student_fees_status_enum" NOT NULL DEFAULT 'PENDING', "due_date" date, "reminder_threshold_date" date, "is_advance_payment" boolean NOT NULL DEFAULT false, "original_advance_month" integer, "original_advance_year" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_4ab7f49422cab5d6df391f9490f" UNIQUE ("student_id", "academic_year_id", "month", "year"), CONSTRAINT "CHK_14a0bf3f656dacb98615d013e7" CHECK ("year" > 0), CONSTRAINT "CHK_fc7527d9e64e4d01667febc89f" CHECK ("month" BETWEEN 1 AND 12), CONSTRAINT "PK_a2cec5273eddb36c724e226cf13" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "student_fees" ADD CONSTRAINT "CHK_sf_total_amount" CHECK ("total_amount" > 0)`);
        await queryRunner.query(`ALTER TABLE "student_fees" ADD CONSTRAINT "CHK_sf_paid_amount" CHECK ("paid_amount" >= 0)`);
        await queryRunner.query(`ALTER TABLE "student_fees" ADD CONSTRAINT "CHK_sf_discount" CHECK ("discount_amount" >= 0)`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('DRAFT', 'ISSUED', 'PAID', 'CANCELLED', 'OVERDUE')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_number" character varying(50) NOT NULL, "student_id" uuid NOT NULL, "student_fee_id" uuid, "total_amount" numeric(10,2) NOT NULL, "tax_amount" numeric(10,2) NOT NULL DEFAULT '0', "discount_amount" numeric(10,2) NOT NULL DEFAULT '0', "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'DRAFT', "issued_date" date NOT NULL, "due_date" date NOT NULL, "line_items" jsonb, "issued_by_user_id" uuid, "notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_d8f8d3788694e1b3f96c42c36fb" UNIQUE ("invoice_number"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "CHK_inv_total_amount" CHECK ("total_amount" > 0)`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "CHK_inv_tax_amount" CHECK ("tax_amount" >= 0)`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "CHK_inv_discount" CHECK ("discount_amount" >= 0)`);
        await queryRunner.query(`CREATE TYPE "public"."payments_payment_method_enum" AS ENUM('CASH', 'CHEQUE', 'BANK_TRANSFER', 'ONLINE', 'CARD', 'UPI')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_payment_status_enum" AS ENUM('SUCCESS', 'PENDING', 'FAILED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "student_id" uuid NOT NULL, "total_amount" numeric(10,2) NOT NULL, "payment_method" "public"."payments_payment_method_enum" NOT NULL, "payment_status" "public"."payments_payment_status_enum" NOT NULL DEFAULT 'SUCCESS', "transaction_reference" character varying(100), "remarks" text, "received_by_user_id" uuid, "invoice_id" uuid, "payment_date" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "CHK_pay_total_amount" CHECK ("total_amount" > 0)`);
        await queryRunner.query(`CREATE INDEX "IDX_1237daf748b7653a6ebb9492fe" ON "payments" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_563a5e248518c623eebd987d43" ON "payments" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9fd5d6ef620b0140a67ff2d95c" ON "payments" ("student_id") `);
        await queryRunner.query(`CREATE TYPE "public"."payment_allocations_allocation_type_enum" AS ENUM('DUE', 'CURRENT', 'ADVANCE')`);
        await queryRunner.query(`CREATE TABLE "payment_allocations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payment_id" uuid NOT NULL, "student_fee_id" uuid NOT NULL, "allocated_amount" numeric(10,2) NOT NULL, "allocation_type" "public"."payment_allocations_allocation_type_enum" NOT NULL, "notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a5c6ff22065ac772620c85f4efb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" ADD CONSTRAINT "CHK_pa_allocated_amount" CHECK ("allocated_amount" > 0)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_89d61f92f4a1fd31f8a120a890" ON "payment_allocations" ("payment_id", "student_fee_id") `);
        await queryRunner.query(`CREATE TYPE "public"."fee_structures_fee_type_enum" AS ENUM('MONTHLY_TUITION', 'EXAM_FEE', 'LIBRARY_FEE', 'LAB_FEE', 'SPORTS_FEE', 'COMPUTER_FEE', 'TRANSPORT_FEE', 'ANNUAL_FEE', 'ADMISSION_FEE', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."fee_structures_applicability_enum" AS ENUM('ALL', 'SELECTED')`);
        await queryRunner.query(`CREATE TABLE "fee_structures" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fee_type" "public"."fee_structures_fee_type_enum" NOT NULL, "name" character varying(100) NOT NULL, "amount" numeric(10,2) NOT NULL, "applicability" "public"."fee_structures_applicability_enum" NOT NULL DEFAULT 'ALL', "class_id" uuid NOT NULL, "section_id" uuid, "academic_year_id" uuid NOT NULL, "month" integer NOT NULL, "is_recurring" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d634078deb9cf5ceb5788ad9b53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "fee_structures" ADD CONSTRAINT "CHK_fs_amount" CHECK ("amount" > 0)`);
        await queryRunner.query(`CREATE INDEX "IDX_ab5ec41d9b29b41a3959177bef" ON "fee_structures" ("class_id", "fee_type", "month") `);
        await queryRunner.query(`CREATE TABLE "fee_structure_students" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fee_structure_id" uuid NOT NULL, "student_id" uuid NOT NULL, CONSTRAINT "PK_6f6400fc17ec79ced2445758c71" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_54a89691bc959d500a12e54304" ON "fee_structure_students" ("fee_structure_id", "student_id") `);
        await queryRunner.query(`CREATE TYPE "public"."reminder_batches_status_enum" AS ENUM('PROCESSING', 'COMPLETED', 'PARTIALLY_FAILED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "reminder_batches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "batch_name" character varying(200) NOT NULL, "status" "public"."reminder_batches_status_enum" NOT NULL DEFAULT 'PROCESSING', "total_recipients" integer NOT NULL, "successful_count" integer NOT NULL DEFAULT '0', "failed_count" integer NOT NULL DEFAULT '0', "message_template" text, "initiated_by_user_id" uuid NOT NULL, "filters_applied" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_02a7d23b0dc125e20a2c4584048" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."communication_logs_medium_enum" AS ENUM('SMS', 'WHATSAPP', 'EMAIL', 'PHONE_CALL', 'MESSENGER')`);
        await queryRunner.query(`CREATE TYPE "public"."communication_logs_status_enum" AS ENUM('QUEUED', 'SENT', 'DELIVERED', 'FAILED', 'READ')`);
        await queryRunner.query(`CREATE TYPE "public"."communication_logs_trigger_enum" AS ENUM('MANUAL', 'AUTOMATED', 'BULK_REMINDER')`);
        await queryRunner.query(`CREATE TABLE "communication_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "medium" "public"."communication_logs_medium_enum" NOT NULL, "recipient_address" character varying(255) NOT NULL, "recipient_name" character varying(100) NOT NULL, "message_body" text NOT NULL, "subject" character varying(200), "status" "public"."communication_logs_status_enum" NOT NULL DEFAULT 'QUEUED', "trigger" "public"."communication_logs_trigger_enum" NOT NULL DEFAULT 'MANUAL', "student_id" uuid, "guardian_id" uuid, "sent_by_user_id" uuid, "provider_message_id" character varying(255), "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d20f31e44aa2108bd47d7a6f781" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'PAYMENT_RECEIVED', 'INVOICE_GENERATED', 'BULK_UPLOAD', 'REMINDER_SENT', 'FEE_STRUCTURE_CHANGE')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" "public"."audit_logs_action_enum" NOT NULL, "entity_type" character varying(100) NOT NULL, "entity_id" uuid, "performed_by_user_id" uuid, "old_values" jsonb, "new_values" jsonb, "ip_address" character varying(45), "user_agent" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."teachers_designations_enum" AS ENUM('CLASS_TEACHER', 'SUBJECT_TEACHER', 'HEAD_TEACHER', 'ASSISTANT_TEACHER', 'PRINCIPAL', 'VICE_PRINCIPAL', 'COORDINATOR')`);
        await queryRunner.query(`CREATE TABLE "teachers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "employee_id" character varying(50) NOT NULL, "designations" "public"."teachers_designations_enum" array NOT NULL DEFAULT '{}', "subject_specialization" character varying(100), "joining_date" date, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_41a9b4d0b9007c9630463244316" UNIQUE ("employee_id"), CONSTRAINT "REL_4668d4752e6766682d1be0b346" UNIQUE ("user_id"), CONSTRAINT "PK_a8d4f83be3abe4c687b0a0093c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "student_guardians" ("student_id" uuid NOT NULL, "guardian_id" uuid NOT NULL, CONSTRAINT "PK_aa0b42c8310d3fb35b846bdce5b" PRIMARY KEY ("student_id", "guardian_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8194052bdd62204f061dd44e0c" ON "student_guardians" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ec3cd56a2093be19f778af57c6" ON "student_guardians" ("guardian_id") `);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_28b990f2f869e1d1652a15388f5" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_sections" ADD CONSTRAINT "FK_686a975f76c959428d568702f8c" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guardians" ADD CONSTRAINT "FK_f1d05a3a2d70db0a25479b67189" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_fb3eff90b11bddf7285f9b4e281" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_a237561608fd252c1785bf3cab9" FOREIGN KEY ("class_section_id") REFERENCES "class_sections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_fees" ADD CONSTRAINT "FK_9e8969b8c743de99403b16b592c" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_fees" ADD CONSTRAINT "FK_a84c5d5305c800b81f39f3f91da" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_0a19069218ffe36a4e4b41c4870" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_ef57e3b4f3e8f4e1ce5b22fb6a5" FOREIGN KEY ("student_fee_id") REFERENCES "student_fees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_413348c9445e63352f10b9a95af" FOREIGN KEY ("issued_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_9fd5d6ef620b0140a67ff2d95c4" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_2d41a84786b3feea87bf36e5da1" FOREIGN KEY ("received_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_563a5e248518c623eebd987d43e" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" ADD CONSTRAINT "FK_4348f49c6822420b9503ba880b8" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" ADD CONSTRAINT "FK_814c351b1a6d9d34dc75e759aba" FOREIGN KEY ("student_fee_id") REFERENCES "student_fees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fee_structures" ADD CONSTRAINT "FK_e8d5f252faed8dfe19f49bbd780" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fee_structures" ADD CONSTRAINT "FK_d346de58f51397c740951aa6f90" FOREIGN KEY ("section_id") REFERENCES "class_sections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fee_structures" ADD CONSTRAINT "FK_4649c7e79b41c39871d78afe0e4" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fee_structure_students" ADD CONSTRAINT "FK_2d58bce35698f9ef3ae53f25ad5" FOREIGN KEY ("fee_structure_id") REFERENCES "fee_structures"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fee_structure_students" ADD CONSTRAINT "FK_0bba5c26c81b56fabfc8246901e" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reminder_batches" ADD CONSTRAINT "FK_ca037cc1f4357fa89c3cb47de63" FOREIGN KEY ("initiated_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "communication_logs" ADD CONSTRAINT "FK_ea33dd96eed5725a899e5b57c61" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "communication_logs" ADD CONSTRAINT "FK_9a858b35ed397526ae7b255fb71" FOREIGN KEY ("guardian_id") REFERENCES "guardians"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "communication_logs" ADD CONSTRAINT "FK_34060a378ca7842e51fb5719a96" FOREIGN KEY ("sent_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_01bc6096ff0db511ac3df6e1e20" FOREIGN KEY ("performed_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`CREATE OR REPLACE FUNCTION "public"."block_audit_logs_write_only"() RETURNS TRIGGER AS $$ BEGIN RAISE EXCEPTION 'audit_logs is write-only: updates and deletes are not permitted'; END; $$ LANGUAGE plpgsql`);
        await queryRunner.query(`CREATE TRIGGER "trg_audit_logs_write_only" BEFORE UPDATE OR DELETE ON "audit_logs" FOR EACH ROW EXECUTE FUNCTION "public"."block_audit_logs_write_only"()`);
        await queryRunner.query(`ALTER TABLE "teachers" ADD CONSTRAINT "FK_4668d4752e6766682d1be0b346f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_guardians" ADD CONSTRAINT "FK_8194052bdd62204f061dd44e0c9" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "student_guardians" ADD CONSTRAINT "FK_ec3cd56a2093be19f778af57c63" FOREIGN KEY ("guardian_id") REFERENCES "guardians"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "student_guardians" DROP CONSTRAINT "FK_ec3cd56a2093be19f778af57c63"`);
        await queryRunner.query(`ALTER TABLE "student_guardians" DROP CONSTRAINT "FK_8194052bdd62204f061dd44e0c9"`);
        await queryRunner.query(`ALTER TABLE "teachers" DROP CONSTRAINT "FK_4668d4752e6766682d1be0b346f"`);
        await queryRunner.query(`DROP TRIGGER IF EXISTS "trg_audit_logs_write_only" ON "audit_logs"`);
        await queryRunner.query(`DROP FUNCTION IF EXISTS "public"."block_audit_logs_write_only"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_01bc6096ff0db511ac3df6e1e20"`);
        await queryRunner.query(`ALTER TABLE "communication_logs" DROP CONSTRAINT "FK_34060a378ca7842e51fb5719a96"`);
        await queryRunner.query(`ALTER TABLE "communication_logs" DROP CONSTRAINT "FK_9a858b35ed397526ae7b255fb71"`);
        await queryRunner.query(`ALTER TABLE "communication_logs" DROP CONSTRAINT "FK_ea33dd96eed5725a899e5b57c61"`);
        await queryRunner.query(`ALTER TABLE "reminder_batches" DROP CONSTRAINT "FK_ca037cc1f4357fa89c3cb47de63"`);
        await queryRunner.query(`ALTER TABLE "fee_structure_students" DROP CONSTRAINT "FK_0bba5c26c81b56fabfc8246901e"`);
        await queryRunner.query(`ALTER TABLE "fee_structure_students" DROP CONSTRAINT "FK_2d58bce35698f9ef3ae53f25ad5"`);
        await queryRunner.query(`ALTER TABLE "fee_structures" DROP CONSTRAINT "FK_e8d5f252faed8dfe19f49bbd780"`);
        await queryRunner.query(`ALTER TABLE "fee_structures" DROP CONSTRAINT "FK_d346de58f51397c740951aa6f90"`);
        await queryRunner.query(`ALTER TABLE "fee_structures" DROP CONSTRAINT "FK_4649c7e79b41c39871d78afe0e4"`);
        await queryRunner.query(`ALTER TABLE "fee_structures" DROP CONSTRAINT "CHK_fs_amount"`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" DROP CONSTRAINT "FK_814c351b1a6d9d34dc75e759aba"`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" DROP CONSTRAINT "FK_4348f49c6822420b9503ba880b8"`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" DROP CONSTRAINT "CHK_pa_allocated_amount"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_563a5e248518c623eebd987d43e"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_2d41a84786b3feea87bf36e5da1"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_9fd5d6ef620b0140a67ff2d95c4"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "CHK_pay_total_amount"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_413348c9445e63352f10b9a95af"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_ef57e3b4f3e8f4e1ce5b22fb6a5"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_0a19069218ffe36a4e4b41c4870"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "CHK_inv_total_amount"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "CHK_inv_tax_amount"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "CHK_inv_discount"`);
        await queryRunner.query(`ALTER TABLE "student_fees" DROP CONSTRAINT "FK_a84c5d5305c800b81f39f3f91da"`);
        await queryRunner.query(`ALTER TABLE "student_fees" DROP CONSTRAINT "FK_9e8969b8c743de99403b16b592c"`);
        await queryRunner.query(`ALTER TABLE "student_fees" DROP CONSTRAINT "CHK_sf_total_amount"`);
        await queryRunner.query(`ALTER TABLE "student_fees" DROP CONSTRAINT "CHK_sf_paid_amount"`);
        await queryRunner.query(`ALTER TABLE "student_fees" DROP CONSTRAINT "CHK_sf_discount"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_a237561608fd252c1785bf3cab9"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_fb3eff90b11bddf7285f9b4e281"`);
        await queryRunner.query(`ALTER TABLE "guardians" DROP CONSTRAINT "FK_f1d05a3a2d70db0a25479b67189"`);
        await queryRunner.query(`ALTER TABLE "class_sections" DROP CONSTRAINT "FK_686a975f76c959428d568702f8c"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_28b990f2f869e1d1652a15388f5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec3cd56a2093be19f778af57c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8194052bdd62204f061dd44e0c"`);
        await queryRunner.query(`DROP TABLE "student_guardians"`);
        await queryRunner.query(`DROP TABLE "teachers"`);
        await queryRunner.query(`DROP TYPE "public"."teachers_designations_enum"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP TABLE "communication_logs"`);
        await queryRunner.query(`DROP TYPE "public"."communication_logs_trigger_enum"`);
        await queryRunner.query(`DROP TYPE "public"."communication_logs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."communication_logs_medium_enum"`);
        await queryRunner.query(`DROP TABLE "reminder_batches"`);
        await queryRunner.query(`DROP TYPE "public"."reminder_batches_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54a89691bc959d500a12e54304"`);
        await queryRunner.query(`DROP TABLE "fee_structure_students"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab5ec41d9b29b41a3959177bef"`);
        await queryRunner.query(`ALTER TABLE "fee_structures" DROP CONSTRAINT "CHK_fs_amount"`);
        await queryRunner.query(`DROP TABLE "fee_structures"`);
        await queryRunner.query(`DROP TYPE "public"."fee_structures_applicability_enum"`);
        await queryRunner.query(`DROP TYPE "public"."fee_structures_fee_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89d61f92f4a1fd31f8a120a890"`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" DROP CONSTRAINT "CHK_pa_allocated_amount"`);
        await queryRunner.query(`DROP TABLE "payment_allocations"`);
        await queryRunner.query(`DROP TYPE "public"."payment_allocations_allocation_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9fd5d6ef620b0140a67ff2d95c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_563a5e248518c623eebd987d43"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1237daf748b7653a6ebb9492fe"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "CHK_pay_total_amount"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_payment_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_payment_method_enum"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "CHK_inv_total_amount"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "CHK_inv_tax_amount"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "CHK_inv_discount"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`ALTER TABLE "student_fees" DROP CONSTRAINT "CHK_sf_total_amount"`);
        await queryRunner.query(`ALTER TABLE "student_fees" DROP CONSTRAINT "CHK_sf_paid_amount"`);
        await queryRunner.query(`ALTER TABLE "student_fees" DROP CONSTRAINT "CHK_sf_discount"`);
        await queryRunner.query(`DROP TABLE "student_fees"`);
        await queryRunner.query(`DROP TYPE "public"."student_fees_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca01941430b7d99b013e6c6948"`);
        await queryRunner.query(`DROP TABLE "students"`);
        await queryRunner.query(`DROP TYPE "public"."students_enrollment_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."students_preferred_communication_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0649f376bac8d9709fb4050fac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2822ea52513239fdd508c016e3"`);
        await queryRunner.query(`DROP TABLE "guardians"`);
        await queryRunner.query(`DROP TYPE "public"."guardians_preferred_communication_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_63d2faa7e6351f234ede380634"`);
        await queryRunner.query(`DROP TABLE "class_sections"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94109a89dd3240577e832b96df"`);
        await queryRunner.query(`DROP TABLE "classes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_645d0f115fa85aaecffdc11cba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12a99ca8a701651b6ff5d6612e"`);
        await queryRunner.query(`DROP TABLE "academic_years"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a000cca60bcf04454e72769949"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    }

}
