import {
  ArmchairIcon,
  ArrowBigUpDashIcon,
  AwardIcon,
  BanknoteIcon,
  BellRingIcon,
  BlocksIcon,
  BookOpenIcon,
  BookUserIcon,
  BriefcaseIcon,
  Building2Icon,
  CalendarCheck2Icon,
  CalendarClockIcon,
  CalendarDaysIcon,
  CalendarRangeIcon,
  ChartColumnIcon,
  ChartLineIcon,
  ChartPieIcon,
  ClipboardCheckIcon,
  ClipboardPenLineIcon,
  CreditCardIcon,
  DoorOpenIcon,
  EllipsisIcon,
  FileClockIcon,
  FilePenLineIcon,
  FilePlus2Icon,
  FileSpreadsheetIcon,
  FileStackIcon,
  GavelIcon,
  GraduationCapIcon,
  HandCoinsIcon,
  HistoryIcon,
  HouseIcon,
  IdCardIcon,
  LayersIcon,
  LayoutDashboardIcon,
  MilestoneIcon,
  NotebookPenIcon,
  PenLineIcon,
  PresentationIcon,
  PrinterIcon,
  ReceiptIcon,
  ReceiptTextIcon,
  RepeatIcon,
  ReplaceIcon,
  RulerIcon,
  ScrollTextIcon,
  SchoolIcon,
  SendIcon,
  SettingsIcon,
  ShieldCheckIcon,
  SlidersHorizontalIcon,
  StarIcon,
  TableIcon,
  TreePalmIcon,
  TrendingUpIcon,
  UserCheckIcon,
  UserPlusIcon,
  UserRoundIcon,
  UsersRoundIcon,
  type LucideIcon,
} from 'lucide-react';

import type { StaffNavItemId } from './nav-tree';

/** [31.3.1] One distinct icon per staff nav item (nav-icons.md, D10). A missing id is a compile error. */
export const STAFF_NAV_ICONS: Record<StaffNavItemId, LucideIcon> = {
  dashboard: LayoutDashboardIcon,
  'people.students': GraduationCapIcon,
  'people.guardians': UsersRoundIcon,
  'people.calendar': CalendarDaysIcon,
  'people.staff': BriefcaseIcon,
  'people.programs': MilestoneIcon,
  'people.admissionIntakes': DoorOpenIcon,
  'people.admissionApplicants': UserPlusIcon,
  'people.admissionReports': ChartPieIcon,
  'people.teachingAssignments': PresentationIcon,
  'people.evaluations': StarIcon,
  'academics.academicYears': CalendarRangeIcon,
  'academics.classes': SchoolIcon,
  'academics.routineSetup': SlidersHorizontalIcon,
  'academics.routineBuilder': TableIcon,
  'academics.routineReview': ClipboardCheckIcon,
  'academics.routineSubstitutions': ReplaceIcon,
  'academics.myRoutine': CalendarClockIcon,
  'academics.myClass': BookUserIcon,
  'academics.homework': NotebookPenIcon,
  'academics.syllabus': BookOpenIcon,
  'attendance.attendance': CalendarCheck2Icon,
  'attendance.attendanceReports': ChartLineIcon,
  'attendance.attendanceRegister': FileSpreadsheetIcon,
  'attendance.staffAttendance': UserCheckIcon,
  'examsResults.exams': FilePenLineIcon,
  'examsResults.examTemplates': FileStackIcon,
  'examsResults.marksEntry': PenLineIcon,
  'examsResults.seatPlans': ArmchairIcon,
  'examsResults.gradingScales': RulerIcon,
  'examsResults.results': AwardIcon,
  'examsResults.analysis': TrendingUpIcon,
  'examsResults.promotion': ArrowBigUpDashIcon,
  'finance.dues': HandCoinsIcon,
  'finance.recordPayment': BanknoteIcon,
  'finance.feeStructures': LayersIcon,
  'finance.generateFees': FilePlus2Icon,
  'finance.recurringSchedules': RepeatIcon,
  'finance.fines': GavelIcon,
  'finance.payments': ReceiptTextIcon,
  'finance.invoices': ReceiptIcon,
  'reports.collectionsReport': ChartColumnIcon,
  'reports.printables': PrinterIcon,
  'communications.sendMessage': SendIcon,
  'communications.feeReminders': BellRingIcon,
  'communications.reminderHistory': HistoryIcon,
  'administration.printTemplates': IdCardIcon,
  'administration.roles': ShieldCheckIcon,
  'administration.auditLogs': ScrollTextIcon,
  'administration.settings': SettingsIcon,
  'administration.curriculumPreset': BlocksIcon,
};

/** The platform console's two pages (also appended to SUPER_ADMIN's staff sidebar). */
export const PLATFORM_NAV_ICONS = {
  '/schools': Building2Icon,
  '/holiday-sets': TreePalmIcon,
} as const;
export const STAFF_PLATFORM_EXTRA_ICONS = PLATFORM_NAV_ICONS;

export const PORTAL_NAV_ICONS: Record<string, LucideIcon> = {
  '/portal': HouseIcon,
  '/portal/fees': CreditCardIcon,
  '/portal/attendance': CalendarCheck2Icon,
  '/portal/routine': CalendarClockIcon,
  '/portal/calendar': CalendarDaysIcon,
  '/portal/results': AwardIcon,
  '/portal/programs': MilestoneIcon,
  '/portal/exam-schedule': FileClockIcon,
  '/portal/syllabus': BookOpenIcon,
  '/portal/surveys': ClipboardPenLineIcon,
  '/portal/account': UserRoundIcon,
};

export const MORE_ICON = EllipsisIcon;
