/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffRouteImport } from './routes/_staff'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as SelectSchoolRouteImport } from './routes/select-school'
import { Route as StaffDashboardRouteImport } from './routes/_staff/dashboard'
import { Route as StaffFeesRouteImport } from './routes/_staff/fees'
import { Route as StaffSettingsRouteImport } from './routes/_staff/settings'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalFeesRouteImport } from './routes/portal/fees'
import { Route as StaffFeesIndexRouteImport } from './routes/_staff/fees/index'
import { Route as StaffFeesDuesRouteImport } from './routes/_staff/fees/dues'
import { Route as StaffInvoicesInvoiceIdRouteImport } from './routes/_staff/invoices/$invoiceId'
import { Route as StaffPaymentsRecordRouteImport } from './routes/_staff/payments/record'
import { Route as StaffStudentsIndexRouteImport } from './routes/_staff/students/index'
import { Route as StaffStudentsStudentIdRouteImport } from './routes/_staff/students/$studentId'
import { Route as StaffStudentsNewRouteImport } from './routes/_staff/students/new'
import { Route as StaffStudentsStudentIdEditRouteImport } from './routes/_staff/students/$studentId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/_staff',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectSchoolRoute = SelectSchoolRouteImport.update({
  id: '/select-school',
  path: '/select-school',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFeesRoute = StaffFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => StaffRoute,
} as any)
const StaffSettingsRoute = StaffSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StaffRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFeesRoute = PortalFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => PortalRoute,
} as any)
const StaffFeesIndexRoute = StaffFeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffFeesRoute,
} as any)
const StaffFeesDuesRoute = StaffFeesDuesRouteImport.update({
  id: '/dues',
  path: '/dues',
  getParentRoute: () => StaffFeesRoute,
} as any)
const StaffInvoicesInvoiceIdRoute = StaffInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPaymentsRecordRoute = StaffPaymentsRecordRouteImport.update({
  id: '/payments/record',
  path: '/payments/record',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStudentsIndexRoute = StaffStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStudentsStudentIdRoute = StaffStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStudentsNewRoute = StaffStudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStudentsStudentIdEditRoute =
  StaffStudentsStudentIdEditRouteImport.update({
    id: '/students/$studentId_/edit',
    path: '/students/$studentId/edit',
    getParentRoute: () => StaffRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/select-school': typeof SelectSchoolRoute
  '/dashboard': typeof StaffDashboardRoute
  '/fees': typeof StaffFeesRouteWithChildren
  '/settings': typeof StaffSettingsRoute
  '/portal/fees': typeof PortalFeesRoute
  '/portal/': typeof PortalIndexRoute
  '/fees/dues': typeof StaffFeesDuesRoute
  '/invoices/$invoiceId': typeof StaffInvoicesInvoiceIdRoute
  '/payments/record': typeof StaffPaymentsRecordRoute
  '/students/$studentId': typeof StaffStudentsStudentIdRoute
  '/students/new': typeof StaffStudentsNewRoute
  '/fees/': typeof StaffFeesIndexRoute
  '/students/': typeof StaffStudentsIndexRoute
  '/students/$studentId/edit': typeof StaffStudentsStudentIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/select-school': typeof SelectSchoolRoute
  '/dashboard': typeof StaffDashboardRoute
  '/settings': typeof StaffSettingsRoute
  '/portal/fees': typeof PortalFeesRoute
  '/portal': typeof PortalIndexRoute
  '/fees/dues': typeof StaffFeesDuesRoute
  '/invoices/$invoiceId': typeof StaffInvoicesInvoiceIdRoute
  '/payments/record': typeof StaffPaymentsRecordRoute
  '/students/$studentId': typeof StaffStudentsStudentIdRoute
  '/students/new': typeof StaffStudentsNewRoute
  '/fees': typeof StaffFeesIndexRoute
  '/students': typeof StaffStudentsIndexRoute
  '/students/$studentId/edit': typeof StaffStudentsStudentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_staff': typeof StaffRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/select-school': typeof SelectSchoolRoute
  '/_staff/dashboard': typeof StaffDashboardRoute
  '/_staff/fees': typeof StaffFeesRouteWithChildren
  '/_staff/settings': typeof StaffSettingsRoute
  '/portal/fees': typeof PortalFeesRoute
  '/portal/': typeof PortalIndexRoute
  '/_staff/fees/dues': typeof StaffFeesDuesRoute
  '/_staff/invoices/$invoiceId': typeof StaffInvoicesInvoiceIdRoute
  '/_staff/payments/record': typeof StaffPaymentsRecordRoute
  '/_staff/students/$studentId': typeof StaffStudentsStudentIdRoute
  '/_staff/students/new': typeof StaffStudentsNewRoute
  '/_staff/fees/': typeof StaffFeesIndexRoute
  '/_staff/students/': typeof StaffStudentsIndexRoute
  '/_staff/students/$studentId_/edit': typeof StaffStudentsStudentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portal'
    | '/select-school'
    | '/dashboard'
    | '/fees'
    | '/settings'
    | '/portal/fees'
    | '/portal/'
    | '/fees/dues'
    | '/invoices/$invoiceId'
    | '/payments/record'
    | '/students/$studentId'
    | '/students/new'
    | '/fees/'
    | '/students/'
    | '/students/$studentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/select-school'
    | '/dashboard'
    | '/settings'
    | '/portal/fees'
    | '/portal'
    | '/fees/dues'
    | '/invoices/$invoiceId'
    | '/payments/record'
    | '/students/$studentId'
    | '/students/new'
    | '/fees'
    | '/students'
    | '/students/$studentId/edit'
  id:
    | '__root__'
    | '/'
    | '/_staff'
    | '/login'
    | '/portal'
    | '/select-school'
    | '/_staff/dashboard'
    | '/_staff/fees'
    | '/_staff/settings'
    | '/portal/fees'
    | '/portal/'
    | '/_staff/fees/dues'
    | '/_staff/invoices/$invoiceId'
    | '/_staff/payments/record'
    | '/_staff/students/$studentId'
    | '/_staff/students/new'
    | '/_staff/fees/'
    | '/_staff/students/'
    | '/_staff/students/$studentId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StaffRoute: typeof StaffRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  SelectSchoolRoute: typeof SelectSchoolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff': {
      id: '/_staff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-school': {
      id: '/select-school'
      path: '/select-school'
      fullPath: '/select-school'
      preLoaderRoute: typeof SelectSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff/dashboard': {
      id: '/_staff/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/fees': {
      id: '/_staff/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof StaffFeesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/settings': {
      id: '/_staff/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof StaffSettingsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/fees': {
      id: '/portal/fees'
      path: '/fees'
      fullPath: '/portal/fees'
      preLoaderRoute: typeof PortalFeesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_staff/fees/': {
      id: '/_staff/fees/'
      path: '/'
      fullPath: '/fees/'
      preLoaderRoute: typeof StaffFeesIndexRouteImport
      parentRoute: typeof StaffFeesRoute
    }
    '/_staff/fees/dues': {
      id: '/_staff/fees/dues'
      path: '/dues'
      fullPath: '/fees/dues'
      preLoaderRoute: typeof StaffFeesDuesRouteImport
      parentRoute: typeof StaffFeesRoute
    }
    '/_staff/invoices/$invoiceId': {
      id: '/_staff/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof StaffInvoicesInvoiceIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/payments/record': {
      id: '/_staff/payments/record'
      path: '/payments/record'
      fullPath: '/payments/record'
      preLoaderRoute: typeof StaffPaymentsRecordRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/students/': {
      id: '/_staff/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StaffStudentsIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/students/$studentId': {
      id: '/_staff/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StaffStudentsStudentIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/students/new': {
      id: '/_staff/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof StaffStudentsNewRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/students/$studentId_/edit': {
      id: '/_staff/students/$studentId_/edit'
      path: '/students/$studentId/edit'
      fullPath: '/students/$studentId/edit'
      preLoaderRoute: typeof StaffStudentsStudentIdEditRouteImport
      parentRoute: typeof StaffRoute
    }
  }
}

interface StaffFeesRouteChildren {
  StaffFeesDuesRoute: typeof StaffFeesDuesRoute
  StaffFeesIndexRoute: typeof StaffFeesIndexRoute
}

const StaffFeesRouteChildren: StaffFeesRouteChildren = {
  StaffFeesDuesRoute: StaffFeesDuesRoute,
  StaffFeesIndexRoute: StaffFeesIndexRoute,
}

const StaffFeesRouteWithChildren = StaffFeesRoute._addFileChildren(
  StaffFeesRouteChildren,
)

interface StaffRouteChildren {
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffFeesRoute: typeof StaffFeesRouteWithChildren
  StaffSettingsRoute: typeof StaffSettingsRoute
  StaffInvoicesInvoiceIdRoute: typeof StaffInvoicesInvoiceIdRoute
  StaffPaymentsRecordRoute: typeof StaffPaymentsRecordRoute
  StaffStudentsStudentIdRoute: typeof StaffStudentsStudentIdRoute
  StaffStudentsNewRoute: typeof StaffStudentsNewRoute
  StaffStudentsIndexRoute: typeof StaffStudentsIndexRoute
  StaffStudentsStudentIdEditRoute: typeof StaffStudentsStudentIdEditRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffDashboardRoute: StaffDashboardRoute,
  StaffFeesRoute: StaffFeesRouteWithChildren,
  StaffSettingsRoute: StaffSettingsRoute,
  StaffInvoicesInvoiceIdRoute: StaffInvoicesInvoiceIdRoute,
  StaffPaymentsRecordRoute: StaffPaymentsRecordRoute,
  StaffStudentsStudentIdRoute: StaffStudentsStudentIdRoute,
  StaffStudentsNewRoute: StaffStudentsNewRoute,
  StaffStudentsIndexRoute: StaffStudentsIndexRoute,
  StaffStudentsStudentIdEditRoute: StaffStudentsStudentIdEditRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface PortalRouteChildren {
  PortalFeesRoute: typeof PortalFeesRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalFeesRoute: PortalFeesRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StaffRoute: StaffRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  SelectSchoolRoute: SelectSchoolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
