/**
 * Storybook 8 config for `@beton-boi/ui` — [8.6.1].
 *
 * Uses the same Vite plugins (`@vitejs/plugin-react`, `@tailwindcss/vite`) and
 * path aliases as the real consuming apps' `vite.config.ts` (see
 * `client-admin/vite.config.ts`), not a copy of `vitest.config.ts`'s aliases —
 * Storybook builds and serves stories through Vite itself, the same pipeline
 * an SPA uses, whereas the root `vitest.config.ts` aliases only exist to keep
 * Vitest's own bundled Vite out of the picture (see that file's header
 * comment). Stories should see exactly what an app sees.
 */
import { resolve } from 'node:path';

import type { StorybookConfig } from '@storybook/react-vite';
import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import { mergeConfig } from 'vite';

const config: StorybookConfig = {
  stories: ['../src/**/*.stories.@(ts|tsx)'],
  addons: ['@storybook/addon-essentials', '@storybook/addon-interactions', '@storybook/addon-a11y'],
  framework: {
    name: '@storybook/react-vite',
    options: {},
  },
  core: {
    disableTelemetry: true,
  },
  // Serves `mockServiceWorker.js` (generated by `npx msw init`, see
  // `package.json`'s `msw.workerDirectory`) at the iframe root so
  // `msw-storybook-addon`'s default `serviceWorker.url` resolves it.
  staticDirs: ['./public'],
  docs: {
    autodocs: 'tag',
  },
  async viteFinal(viteConfig) {
    return mergeConfig(viteConfig, {
      plugins: [react(), tailwindcss()],
      resolve: {
        alias: {
          '@': resolve(__dirname, '../src'),
          '@beton-boi/shared': resolve(__dirname, '../../shared/src'),
        },
      },
    });
  },
};

export default config;
